source "http://rubygems.org"

# Default Rails dependencies
gem "rails", "3.2.3"
gem "jquery-rails"

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier',     "~> 1.0.3"
end

# Stratify-specific dependencies
gem "stratify-base",       :path => "/Users/jason/src/stratify/stratify-base"
gem "stratify-foursquare", :path => "/Users/jason/src/stratify/stratify-foursquare"
gem "stratify-garmin",     :path => "/Users/jason/src/stratify/stratify-garmin"
gem "stratify-gowalla",    :path => "/Users/jason/src/stratify/stratify-gowalla"
gem "stratify-instapaper", :path => "/Users/jason/src/stratify/stratify-instapaper"
gem "stratify-itunes",     :path => "/Users/jason/src/stratify/stratify-itunes"
gem "stratify-rhapsody",   :path => "/Users/jason/src/stratify/stratify-rhapsody"
gem "stratify-twitter",    :path => "/Users/jason/src/stratify/stratify-twitter"
gem "kaminari"
gem "mongoid_rails_migrations"
gem 'whenever', :require => false
gem 'capistrano' # for deployment

group "development", "test" do
  gem "factory_girl_rails"
  gem "faker"
  gem "rspec-rails"
end

group "test" do
  gem "capybara", "~> 1.0.0.beta1"
  gem "database_cleaner"
  gem "fakeweb"
  gem "growl" # for Guard notifications
  gem "guard-rspec"
  gem "guard-spork"
  gem "launchy"
  gem "mocha"
  gem "rb-fsevent", :require => false if RUBY_PLATFORM =~ /darwin/i
  gem "spork"
end
