require 'spec_helper'

# TODO Patch Stratify base to include this change.  Add a spec for it.
module Stratify
  class << self
    def logger
      @logger ||= initialize_logger
    end

    private
    
    def initialize_logger
      return Rails.logger if (defined?(Rails) && Rails.logger)
      Logger.new(STDOUT)
    end    
  end
end


describe "stratify-foursquare" do
  use_vcr_cassette "foursquare"

  it "collects and stores data from foursquare", :database => true do
    collector = Stratify::Foursquare::Collector.create!(:oauth_token => 'NEFB1MA3VGSHFEGJ4YW0JESYWRXMREUEMZCRGGYO34XECCGK') # TODO anonymize
    collector.run

    p Stratify::Foursquare::Activity.where(:checkin_id => "4e85118c6c25709c5f998be5").all.to_a

    Stratify::Foursquare::Activity.where(
      :checkin_id => "4e85118c6c25709c5f998be5",
      :venue_id => "4ba41d75f964a520108338e3",
      :venue_name => "Cochon",
      :venue_street => "930 Tchoupitoulas St",
      :venue_city => "New Orleans",
      :venue_state => "LA",
      :venue_country => "USA",
      :venue_latitude => 29.942296295356602,
      :venue_longitude => -90.06738245487213,
      # :created_at => Time.parse("Thu, 29 Sep 2011 19:47:08 CDT") # TODO
    ).should exist

    # TODO Add assertion for very simple checkin
    # Stratify::Foursquare::Activity.where(
    #   :checkin_id => 26999668,
    #   :spot_name => "Starbucks",
    #   :created_at => Time.parse("2011-01-20T21:35:25Z")
    # ).should exist
  end
end


# -----------------------------------------------------

{"count"=>17,
 "items"=>
  [{"id"=>"4e85dfc002d58a685e9aade7",
    "createdAt"=>1317396416,
    "type"=>"checkin",
    "timeZone"=>"America/Chicago",
    "entities"=>[],
    "venue"=>
     {"id"=>"4e84782130f8918c6a8a5e05",
      "name"=>"Rubyconf 2011",
      "contact"=>{},
      "location"=>
       {"address"=>"739 Canal St",
        "lat"=>29.954438,
        "lng"=>-90.069349,
        "city"=>"New Orleans",
        "state"=>"LA"},
      "categories"=>
       [{"id"=>"4bf58dd8d48988d1ff931735",
         "name"=>"Convention Center",
         "pluralName"=>"Convention Centers",
         "shortName"=>"Convention Center",
         "icon"=>"https://foursquare.com/img/categories/building/default.png",
         "parents"=>["Professional & Other Places"],
         "primary"=>true}],
      "verified"=>false,
      "stats"=>{"checkinsCount"=>27, "usersCount"=>24, "tipCount"=>0}},
    "photos"=>{"count"=>0, "items"=>[]},
    "comments"=>{"count"=>0, "items"=>[]},
    "source"=>
     {"name"=>"foursquare for iPhone",
      "url"=>"https://foursquare.com/download/#/iphone"}},
   {"id"=>"4e85b49377c8e4e6e12e3533",
    "createdAt"=>1317385363,
    "type"=>"checkin",
    "timeZone"=>"America/Chicago",
    "entities"=>[],
    "venue"=>
     {"id"=>"4ba7748bf964a520479539e3",
      "name"=>"Downtown Fitness Center - Canal Place",
      "contact"=>
       {"phone"=>"5045252956",
        "formattedPhone"=>"(504) 525-2956",
        "twitter"=>"downtownfitNOLA"},
      "location"=>
       {"address"=>"380 One Canal Place",
        "lat"=>29.95169960698807,
        "lng"=>-90.0653600692749,
        "postalCode"=>"70130",
        "city"=>"New Orleans",
        "state"=>"LA",
        "country"=>"USA"},
      "categories"=>
       [{"id"=>"4bf58dd8d48988d176941735",
         "name"=>"Gym",
         "pluralName"=>"Gyms",
         "shortName"=>"Gym",
         "icon"=>"https://foursquare.com/img/categories/building/gym.png",
         "parents"=>["Shops & Services", "Gyms or Fitness Centers"],
         "primary"=>true}],
      "verified"=>true,
      "stats"=>{"checkinsCount"=>333, "usersCount"=>30, "tipCount"=>1},
      "url"=>"http://www.downtownfitnesscenter.com"},
    "photos"=>{"count"=>0, "items"=>[]},
    "comments"=>{"count"=>0, "items"=>[]},
    "source"=>
     {"name"=>"foursquare for iPhone",
      "url"=>"https://foursquare.com/download/#/iphone"}},
   {"id"=>"4e85118c6c25709c5f998be5",
    "createdAt"=>1317343628,
    "type"=>"checkin",
    "timeZone"=>"America/Chicago",
    "entities"=>[],
    "venue"=>
     {"id"=>"4ba41d75f964a520108338e3",
      "name"=>"Cochon",
      "contact"=>{"phone"=>"5045882123", "formattedPhone"=>"(504) 588-2123"},
      "location"=>
       {"address"=>"930 Tchoupitoulas St",
        "crossStreet"=>"at Andrew Higgins Bl",
        "lat"=>29.942296295356602,
        "lng"=>-90.06738245487213,
        "postalCode"=>"70130",
        "city"=>"New Orleans",
        "state"=>"LA",
        "country"=>"USA"},
      "categories"=>
       [{"id"=>"4bf58dd8d48988d14f941735",
         "name"=>"Southern or Soul Food Restaurant",
         "pluralName"=>"Southern or Soul Food Restaurants",
         "shortName"=>"Southern / Soul",
         "icon"=>"https://foursquare.com/img/categories/food/southern.png",
         "parents"=>["Food"],
         "primary"=>true}],
      "verified"=>false,
      "stats"=>{"checkinsCount"=>2047, "usersCount"=>1594, "tipCount"=>43}},
    "photos"=>{"count"=>0, "items"=>[]},
    "comments"=>{"count"=>0, "items"=>[]},
    "source"=>
     {"name"=>"foursquare for iPhone",
      "url"=>"https://foursquare.com/download/#/iphone"}},
   {"id"=>"4e84fd52cc21e9ea905d6b63",
    "createdAt"=>1317338450,
    "type"=>"checkin",
    "timeZone"=>"America/Chicago",
    "entities"=>[],
    "venue"=>
     {"id"=>"4b4660ecf964a520291f26e3",
      "name"=>"Capdeville",
      "contact"=>
       {"phone"=>"5043715161",
        "formattedPhone"=>"(504) 371-5161",
        "twitter"=>"MayorCapdeville"},
      "location"=>
       {"address"=>"520 Capdeville St",
        "crossStreet"=>"btw Camp & Magazine",
        "lat"=>29.947323435882595,
        "lng"=>-90.06926268339157,
        "postalCode"=>"70130",
        "city"=>"New Orleans",
        "state"=>"LA",
        "country"=>"USA"},
      "categories"=>
       [{"id"=>"4bf58dd8d48988d157941735",
         "name"=>"New American Restaurant",
         "pluralName"=>"New American Restaurants",
         "shortName"=>"New American",
         "icon"=>"https://foursquare.com/img/categories/food/default.png",
         "parents"=>["Food"],
         "primary"=>true}],
      "verified"=>false,
      "stats"=>{"checkinsCount"=>2783, "usersCount"=>712, "tipCount"=>22}},
    "photos"=>{"count"=>0, "items"=>[]},
    "comments"=>{"count"=>0, "items"=>[]},
    "source"=>
     {"name"=>"foursquare for iPhone",
      "url"=>"https://foursquare.com/download/#/iphone"}},
   {"id"=>"4e84fc588b8175a8a92c1d1a",
    "createdAt"=>1317338200,
    "type"=>"checkin",
    "timeZone"=>"America/Chicago",
    "entities"=>[],
    "venue"=>
     {"id"=>"4ad76ef8f964a5205d0a21e3",
      "name"=>"Lafayette Square",
      "contact"=>
       {"phone"=>"5045851500",
        "formattedPhone"=>"(504) 585-1500",
        "twitter"=>"youngleadership"},
      "location"=>
       {"address"=>"500 St Charles Ave",
        "crossStreet"=>"N Maistre St",
        "lat"=>29.9482042632846,
        "lng"=>-90.07033824920654,
        "postalCode"=>"70113",
        "city"=>"New Orleans",
        "state"=>"LA"},
      "categories"=>
       [{"id"=>"4bf58dd8d48988d163941735",
         "name"=>"Park",
         "pluralName"=>"Parks",
         "shortName"=>"Park",
         "icon"=>
          "https://foursquare.com/img/categories/parks_outdoors/default.png",
         "parents"=>["Great Outdoors"],
         "primary"=>true}],
      "verified"=>false,
      "stats"=>{"checkinsCount"=>1894, "usersCount"=>824, "tipCount"=>9}},
    "photos"=>{"count"=>0, "items"=>[]},
    "comments"=>{"count"=>0, "items"=>[]},
    "source"=>
     {"name"=>"foursquare for iPhone",
      "url"=>"https://foursquare.com/download/#/iphone"}},
   {"id"=>"4e8487a149012a836343eaa1",
    "createdAt"=>1317308321,
    "type"=>"checkin",
    "timeZone"=>"America/Chicago",
    "entities"=>[],
    "venue"=>
     {"id"=>"4e84782130f8918c6a8a5e05",
      "name"=>"Rubyconf 2011",
      "contact"=>{},
      "location"=>
       {"address"=>"739 Canal St",
        "lat"=>29.954438,
        "lng"=>-90.069349,
        "city"=>"New Orleans",
        "state"=>"LA"},
      "categories"=>
       [{"id"=>"4bf58dd8d48988d1ff931735",
         "name"=>"Convention Center",
         "pluralName"=>"Convention Centers",
         "shortName"=>"Convention Center",
         "icon"=>"https://foursquare.com/img/categories/building/default.png",
         "parents"=>["Professional & Other Places"],
         "primary"=>true}],
      "verified"=>false,
      "stats"=>{"checkinsCount"=>27, "usersCount"=>24, "tipCount"=>0}},
    "photos"=>{"count"=>0, "items"=>[]},
    "comments"=>{"count"=>0, "items"=>[]},
    "source"=>
     {"name"=>"foursquare for iPhone",
      "url"=>"https://foursquare.com/download/#/iphone"}},
   {"id"=>"4e83b9a97ee6f75ca2d08246",
    "createdAt"=>1317255593,
    "type"=>"checkin",
    "timeZone"=>"America/Chicago",
    "entities"=>[],
    "venue"=>
     {"id"=>"4ad4c04af964a52081f220e3",
      "name"=>"Astor Crowne Plaza",
      "contact"=>{"phone"=>"5049620500", "formattedPhone"=>"(504) 962-0500"},
      "location"=>
       {"address"=>"739 Canal St",
        "crossStreet"=>"at Bourbon St",
        "lat"=>29.95386089500902,
        "lng"=>-90.06958186626434,
        "postalCode"=>"70130",
        "city"=>"New Orleans",
        "state"=>"LA",
        "country"=>"USA"},
      "categories"=>
       [{"id"=>"4bf58dd8d48988d1fa931735",
         "name"=>"Hotel",
         "pluralName"=>"Hotels",
         "shortName"=>"Hotel",
         "icon"=>"https://foursquare.com/img/categories/travel/hotel.png",
         "parents"=>["Travel Spots"],
         "primary"=>true}],
      "verified"=>false,
      "stats"=>{"checkinsCount"=>2079, "usersCount"=>898, "tipCount"=>12}},
    "photos"=>{"count"=>0, "items"=>[]},
    "comments"=>{"count"=>0, "items"=>[]},
    "source"=>
     {"name"=>"foursquare for iPhone",
      "url"=>"https://foursquare.com/download/#/iphone"}},
   {"id"=>"4e83ab436c2508dd3506a80f",
    "createdAt"=>1317251907,
    "type"=>"checkin",
    "timeZone"=>"America/Chicago",
    "entities"=>[],
    "venue"=>
     {"id"=>"4a65d6a4f964a520a1c71fe3",
      "name"=>"Louis Armstrong New Orleans International Airport",
      "contact"=>
       {"phone"=>"5043037500",
        "formattedPhone"=>"(504) 303-7500",
        "twitter"=>"NO_Airport"},
      "location"=>
       {"address"=>"900 Airline Dr",
        "lat"=>29.984936414376474,
        "lng"=>-90.25714874267578,
        "postalCode"=>"70062",
        "city"=>"Kenner",
        "state"=>"LA",
        "country"=>"USA"},
      "categories"=>
       [{"id"=>"4bf58dd8d48988d1ed931735",
         "name"=>"Airport",
         "pluralName"=>"Airports",
         "shortName"=>"Airport",
         "icon"=>"https://foursquare.com/img/categories/travel/airport.png",
         "parents"=>["Travel Spots"],
         "primary"=>true}],
      "verified"=>true,
      "stats"=>{"checkinsCount"=>56604, "usersCount"=>27014, "tipCount"=>196},
      "url"=>"http://www.flymsy.com"},
    "photos"=>{"count"=>0, "items"=>[]},
    "comments"=>{"count"=>0, "items"=>[]},
    "source"=>
     {"name"=>"foursquare for iPhone",
      "url"=>"https://foursquare.com/download/#/iphone"}},
   {"id"=>"4e83883d722ea2c7b9055477",
    "createdAt"=>1317242941,
    "type"=>"checkin",
    "timeZone"=>"America/New_York",
    "entities"=>[],
    "venue"=>
     {"id"=>"4c65d8f2f7a80f476d8f9c7a",
      "name"=>"Fast Lane",
      "contact"=>{},
      "location"=>
       {"address"=>"Atlanta Airport",
        "crossStreet"=>"in Terminal C",
        "lat"=>33.639975,
        "lng"=>-84.444032,
        "city"=>"Atlanta",
        "state"=>"GA"},
      "categories"=>
       [{"id"=>"4bf58dd8d48988d16c941735",
         "name"=>"Burger Joint",
         "pluralName"=>"Burger Joints",
         "shortName"=>"Burgers",
         "icon"=>"https://foursquare.com/img/categories/food/burger.png",
         "parents"=>["Food"],
         "primary"=>true}],
      "verified"=>false,
      "stats"=>{"checkinsCount"=>21, "usersCount"=>20, "tipCount"=>0}},
    "photos"=>{"count"=>0, "items"=>[]},
    "comments"=>{"count"=>0, "items"=>[]},
    "source"=>
     {"name"=>"foursquare for iPhone",
      "url"=>"https://foursquare.com/download/#/iphone"}},
   {"id"=>"4e838380722ea2c7b903a773",
    "createdAt"=>1317241728,
    "type"=>"checkin",
    "shout"=>"Next stop: New Orleans",
    "timeZone"=>"America/New_York",
    "entities"=>[],
    "venue"=>
     {"id"=>"4a8a103af964a520c90920e3",
      "name"=>"Hartsfield-Jackson Atlanta International Airport (ATL)",
      "contact"=>
       {"phone"=>"4042092920",
        "formattedPhone"=>"(404) 209-2920",
        "twitter"=>"Atlanta_Airport"},
      "location"=>
       {"address"=>"6000 N. Terminal Pkwy.",
        "lat"=>33.640669114843895,
        "lng"=>-84.43606853485107,
        "postalCode"=>"30337",
        "city"=>"Atlanta",
        "state"=>"GA",
        "country"=>"USA"},
      "categories"=>
       [{"id"=>"4bf58dd8d48988d1ed931735",
         "name"=>"Airport",
         "pluralName"=>"Airports",
         "shortName"=>"Airport",
         "icon"=>"https://foursquare.com/img/categories/travel/airport.png",
         "parents"=>["Travel Spots"],
         "primary"=>true}],
      "verified"=>true,
      "stats"=>
       {"checkinsCount"=>348898, "usersCount"=>122770, "tipCount"=>940},
      "url"=>"http://atlanta-airport.com"},
    "photos"=>{"count"=>0, "items"=>[]},
    "comments"=>{"count"=>0, "items"=>[]},
    "source"=>
     {"name"=>"foursquare for iPhone",
      "url"=>"https://foursquare.com/download/#/iphone"}},
   {"id"=>"4e8360716da16e5e98d00721",
    "createdAt"=>1317232753,
    "type"=>"checkin",
    "timeZone"=>"America/New_York",
    "entities"=>[],
    "venue"=>
     {"id"=>"4aa6a083f964a5206c4a20e3",
      "name"=>"Raleigh-Durham International Airport (RDU)",
      "contact"=>
       {"phone"=>"9198402123",
        "formattedPhone"=>"(919) 840-2123",
        "twitter"=>"RDUAirport"},
      "location"=>
       {"address"=>"2400 W. Terminal Blvd.",
        "crossStreet"=>"at Aviation Pkwy.",
        "lat"=>35.877425,
        "lng"=>-78.789078,
        "postalCode"=>"27560",
        "city"=>"Raleigh",
        "state"=>"NC",
        "country"=>"USA"},
      "categories"=>
       [{"id"=>"4bf58dd8d48988d1ed931735",
         "name"=>"Airport",
         "pluralName"=>"Airports",
         "shortName"=>"Airport",
         "icon"=>"https://foursquare.com/img/categories/travel/airport.png",
         "parents"=>["Travel Spots"],
         "primary"=>true}],
      "verified"=>false,
      "stats"=>{"checkinsCount"=>54367, "usersCount"=>19439, "tipCount"=>121},
      "url"=>"http://www.rdu.com"},
    "photos"=>{"count"=>0, "items"=>[]},
    "comments"=>{"count"=>0, "items"=>[]},
    "source"=>
     {"name"=>"foursquare for iPhone",
      "url"=>"https://foursquare.com/download/#/iphone"}},
   {"id"=>"4e82edf98b817f241042bc12",
    "createdAt"=>1317203449,
    "type"=>"checkin",
    "timeZone"=>"America/New_York",
    "entities"=>[],
    "venue"=>
     {"id"=>"4b3a8cc7f964a520bc6925e3",
      "name"=>"Fitness 19",
      "contact"=>{"phone"=>"9198700281", "formattedPhone"=>"(919) 870-0281"},
      "location"=>
       {"address"=>"9101 Leesville Rd",
        "crossStreet"=>"Fairbanks Rd",
        "lat"=>35.89703,
        "lng"=>-78.72530767,
        "postalCode"=>"27613",
        "city"=>"Raleigh",
        "state"=>"NC"},
      "categories"=>
       [{"id"=>"4bf58dd8d48988d176941735",
         "name"=>"Gym",
         "pluralName"=>"Gyms",
         "shortName"=>"Gym",
         "icon"=>"https://foursquare.com/img/categories/building/gym.png",
         "parents"=>["Shops & Services", "Gyms or Fitness Centers"],
         "primary"=>true}],
      "verified"=>false,
      "stats"=>{"checkinsCount"=>590, "usersCount"=>48, "tipCount"=>1}},
    "photos"=>{"count"=>0, "items"=>[]},
    "comments"=>{"count"=>0, "items"=>[]},
    "source"=>
     {"name"=>"foursquare for iPhone",
      "url"=>"https://foursquare.com/download/#/iphone"}},
   {"id"=>"4e81f2c2b63467b4f2c77b06",
    "createdAt"=>1317139138,
    "type"=>"checkin",
    "timeZone"=>"America/New_York",
    "entities"=>[],
    "venue"=>
     {"id"=>"4c6723f3e75ac9280dccf9da",
      "name"=>"El Rodeo @ Brightleaf",
      "contact"=>{},
      "location"=>
       {"address"=>"905 West Main Street",
        "lat"=>35.9996218,
        "lng"=>-78.9097557,
        "postalCode"=>"27701",
        "city"=>"Durham",
        "state"=>"North Carolina"},
      "categories"=>
       [{"id"=>"4bf58dd8d48988d1c1941735",
         "name"=>"Mexican Restaurant",
         "pluralName"=>"Mexican Restaurants",
         "shortName"=>"Mexican",
         "icon"=>"https://foursquare.com/img/categories/food/mexican.png",
         "parents"=>["Food"],
         "primary"=>true}],
      "verified"=>false,
      "stats"=>{"checkinsCount"=>464, "usersCount"=>275, "tipCount"=>2}},
    "photos"=>{"count"=>0, "items"=>[]},
    "comments"=>{"count"=>0, "items"=>[]},
    "source"=>
     {"name"=>"foursquare for iPhone",
      "url"=>"https://foursquare.com/download/#/iphone"}},
   {"id"=>"4e81eff482318487c21b424c",
    "createdAt"=>1317138420,
    "type"=>"checkin",
    "timeZone"=>"America/New_York",
    "entities"=>[],
    "venue"=>
     {"id"=>"4dff475fd4c00c69c14bd793",
      "name"=>"Relevance, Inc",
      "contact"=>{},
      "location"=>
       {"address"=>"514 S Duke St",
        "lat"=>35.99464903333333,
        "lng"=>-78.90908873333333,
        "postalCode"=>"27701",
        "city"=>"Durham",
        "state"=>"North Carolina"},
      "categories"=>
       [{"id"=>"4bf58dd8d48988d124941735",
         "name"=>"Office",
         "pluralName"=>"Offices",
         "shortName"=>"Corporate / Office",
         "icon"=>"https://foursquare.com/img/categories/building/default.png",
         "parents"=>["Professional & Other Places"],
         "primary"=>true}],
      "verified"=>false,
      "stats"=>{"checkinsCount"=>33, "usersCount"=>4, "tipCount"=>0}},
    "photos"=>{"count"=>0, "items"=>[]},
    "comments"=>{"count"=>0, "items"=>[]},
    "source"=>
     {"name"=>"foursquare for iPhone",
      "url"=>"https://foursquare.com/download/#/iphone"}},
   {"id"=>"4e80acd349014ccbd281aabe",
    "createdAt"=>1317055699,
    "type"=>"checkin",
    "private"=>true,
    "timeZone"=>"America/New_York",
    "entities"=>[],
    "venue"=>
     {"id"=>"4b76f4a8f964a520426e2ee3",
      "name"=>"Petco",
      "contact"=>{"phone"=>"9195968838", "formattedPhone"=>"(919) 596-8838"},
      "location"=>
       {"address"=>"7811 Alexander Promenade Place",
        "crossStreet"=>"Brier Creek",
        "lat"=>35.91428764150443,
        "lng"=>-78.77717077732086,
        "postalCode"=>"27617",
        "city"=>"Raleigh",
        "state"=>"NC",
        "country"=>"USA"},
      "categories"=>
       [{"id"=>"4bf58dd8d48988d100951735",
         "name"=>"Pet Store",
         "pluralName"=>"Pet Stores",
         "shortName"=>"Pet Store",
         "icon"=>"https://foursquare.com/img/categories/shops/pet_store.png",
         "parents"=>["Shops & Services"],
         "primary"=>true}],
      "verified"=>false,
      "stats"=>{"checkinsCount"=>203, "usersCount"=>112, "tipCount"=>1}},
    "photos"=>{"count"=>0, "items"=>[]},
    "comments"=>{"count"=>0, "items"=>[]},
    "source"=>
     {"name"=>"foursquare for iPhone",
      "url"=>"https://foursquare.com/download/#/iphone"}},
   {"id"=>"4e80a308b8f7d6b24bd633b0",
    "createdAt"=>1317053192,
    "type"=>"checkin",
    "timeZone"=>"America/New_York",
    "entities"=>[],
    "venue"=>
     {"id"=>"4ad60a6ff964a520b50421e3",
      "name"=>"Panera Bread",
      "contact"=>
       {"phone"=>"9192930900",
        "formattedPhone"=>"(919) 293-0900",
        "twitter"=>"panerabread"},
      "location"=>
       {"address"=>"7840 Alexander Promenade Pl. #100",
        "crossStreet"=>"at Brier Creek Pkwy.",
        "lat"=>35.91389010800875,
        "lng"=>-78.77965182065964,
        "postalCode"=>"27617",
        "city"=>"Raleigh",
        "state"=>"NC",
        "country"=>"USA"},
      "categories"=>
       [{"id"=>"4bf58dd8d48988d16d941735",
         "name"=>"Cafe",
         "pluralName"=>"Cafes",
         "shortName"=>"Cafes",
         "icon"=>"https://foursquare.com/img/categories/food/cafe.png",
         "parents"=>["Food"],
         "primary"=>true}],
      "verified"=>false,
      "stats"=>{"checkinsCount"=>1489, "usersCount"=>601, "tipCount"=>9}},
    "photos"=>{"count"=>0, "items"=>[]},
    "comments"=>{"count"=>0, "items"=>[]},
    "source"=>
     {"name"=>"foursquare for iPhone",
      "url"=>"https://foursquare.com/download/#/iphone"}},
   {"id"=>"4e80493a6da1ef1165fa31af",
    "createdAt"=>1317030202,
    "type"=>"checkin",
    "timeZone"=>"America/New_York",
    "entities"=>[],
    "venue"=>
     {"id"=>"4b3a8cc7f964a520bc6925e3",
      "name"=>"Fitness 19",
      "contact"=>{"phone"=>"9198700281", "formattedPhone"=>"(919) 870-0281"},
      "location"=>
       {"address"=>"9101 Leesville Rd",
        "crossStreet"=>"Fairbanks Rd",
        "lat"=>35.89703,
        "lng"=>-78.72530767,
        "postalCode"=>"27613",
        "city"=>"Raleigh",
        "state"=>"NC"},
      "categories"=>
       [{"id"=>"4bf58dd8d48988d176941735",
         "name"=>"Gym",
         "pluralName"=>"Gyms",
         "shortName"=>"Gym",
         "icon"=>"https://foursquare.com/img/categories/building/gym.png",
         "parents"=>["Shops & Services", "Gyms or Fitness Centers"],
         "primary"=>true}],
      "verified"=>false,
      "stats"=>{"checkinsCount"=>590, "usersCount"=>48, "tipCount"=>1}},
    "photos"=>{"count"=>0, "items"=>[]},
    "comments"=>{"count"=>0, "items"=>[]},
    "source"=>
     {"name"=>"foursquare for iPhone",
      "url"=>"https://foursquare.com/download/#/iphone"}}]}
